// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJOeVAaMoDlK2UIfR5p7ENq--2loaxKuY',
    appId: '1:206078516575:web:241ded90f18b61cdd4eaea',
    messagingSenderId: '206078516575',
    projectId: 'orbit-mvp-54642',
    authDomain: 'orbit-mvp-54642.firebaseapp.com',
    storageBucket: 'orbit-mvp-54642.firebasestorage.app',
    measurementId: 'G-VV9JEFG6KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPBantaIQpl4sBc2X9YD8vqirc3IirctY',
    appId: '1:206078516575:android:0524a76c5ab27130d4eaea',
    messagingSenderId: '206078516575',
    projectId: 'orbit-mvp-54642',
    storageBucket: 'orbit-mvp-54642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWRc5KKzvqrjakaVW7SDFQWZ2r0elu0PU',
    appId: '1:206078516575:ios:35310cd6ab77a3a9d4eaea',
    messagingSenderId: '206078516575',
    projectId: 'orbit-mvp-54642',
    storageBucket: 'orbit-mvp-54642.firebasestorage.app',
    androidClientId: '206078516575-8crne78hp19n6srn5lmg468bjqcp6u5e.apps.googleusercontent.com',
    iosClientId: '206078516575-u53kv74tr0cmpt52l19a4ultdfua45dc.apps.googleusercontent.com',
    iosBundleId: 'com.example.orbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWRc5KKzvqrjakaVW7SDFQWZ2r0elu0PU',
    appId: '1:206078516575:ios:35310cd6ab77a3a9d4eaea',
    messagingSenderId: '206078516575',
    projectId: 'orbit-mvp-54642',
    storageBucket: 'orbit-mvp-54642.firebasestorage.app',
    androidClientId: '206078516575-8crne78hp19n6srn5lmg468bjqcp6u5e.apps.googleusercontent.com',
    iosClientId: '206078516575-u53kv74tr0cmpt52l19a4ultdfua45dc.apps.googleusercontent.com',
    iosBundleId: 'com.example.orbit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJOeVAaMoDlK2UIfR5p7ENq--2loaxKuY',
    appId: '1:206078516575:web:5973e3dd8b89bcd9d4eaea',
    messagingSenderId: '206078516575',
    projectId: 'orbit-mvp-54642',
    authDomain: 'orbit-mvp-54642.firebaseapp.com',
    storageBucket: 'orbit-mvp-54642.firebasestorage.app',
    measurementId: 'G-4WDMEGR558',
  );
}
